apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${loadgen_manifest_app_name}
  namespace: ${namespace}
  labels:
    app: ${loadgen_manifest_app_name}
  annotations:
    ves.io/workload-flavor: tiny
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${loadgen_manifest_app_name}
  template:
    metadata:
      labels:
        app: ${loadgen_manifest_app_name}
    spec:
      containers:
      - image: public.ecr.aws/y6q2t0j9/demos:swapi-loadgen
        imagePullPolicy: IfNotPresent
        name: ${loadgen_manifest_app_name}
        ports:
          - containerPort: 8080
        env:
          - name: TARGET_URL
            value: "http://${manifest_app_name}.${domain}"
